In [2]:
import numpy as np

In [3]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
Y = np.array([0,1,1,0])

In [28]:
W = np.matmul(np.linalg.inv(X.T @ X), X.T @ Y)
print(W)

[0.00000000e+00 2.22044605e-16 5.00000000e-01]


In [42]:
def calc_w(x,y):
  #Acordate que siempre entran en formato columna
  W = 0
  W = np.matmul(np.linalg.inv(x.T @ x), x.T @ y)
  return W

In [44]:
calc_w(X,Y)

array([0.00000000e+00, 2.22044605e-16, 5.00000000e-01])

# Implementacion de la red neuronal de 2 leyers

In [37]:
alfa = 0.01

# Hidden Layer - Neurona 1
w_n1_l1 = np.random.normal(0,1,(3,1)) # dim = 3x1
print('Inicializacion en el leyer 1 de W en la neurona 1: ')
print(w_n1_l1)
print()

x = np.array([[1,0,1]]) # dim 1x3
z1_l1 = x.T * w_n1_l1 # dim 3x1
print('Z1 en el leyer 1 da: ')
print(z1_l1)
print()

a1 = 1/ (1 + np.exp(-1* z1_l1.sum())) # dim 1x1
print('a1 en el leyer 1 da: ')
print(a1)
print()


# Hidden Layer - Neurona 2
w_n2_l1 = np.random.normal(0,1,(3,1))
print('Inicializacion en el leyer 1 de W en la neurona 2: ')
print(w_n2_l1)
print()

x = np.array([[1,0,1]])
z2_l1 = x.T * w_n2_l1
print('Z2 en el leyer 1 da: ')
print(z2_l1)
print()

a2 = 1/ (1 + np.exp(-1* z2_l1.sum()))
print('a2 en el leyer 1 da: ')
print(a2)
print()
# Output Layer - Neurona salida
w_output = np.random.normal(0,1,(3,1))
y_hat = np.array([[a1,a2,1]]) @ w_output
print('y_hat en el output leyer da: ')
print(y_hat)
print()
# Calculo del error 
error = 0 - y_hat

# Actualizacion de los parametros Output Layer

w_output[0] = w_output[0] + alfa * 2 * error * a1
w_output[1] = w_output[1] + alfa * 2 * error * a2
w_output[0] = w_output[2] + alfa * 2 * error 

#w_output = np.array([[w_output[0] + alfa * 2 * error * a1], 
                     #[w_output[1] + alfa * 2 * error * a2], 
                     #[w_output[2] + alfa * 2 * error]])

print('Actualizacion del W en el output layer que da: ')
print(w_output)
print()
# Actualizacion de los parametros del Hidden Layer
w_n1_l1[0] = w_n1_l1[0] + alfa * (-2 * error * w_output[0]) * (a1 * (1 - a1)) * x[0,0]
w_n1_l1[1] = w_n1_l1[1] + alfa * (-2 * error * w_output[1]) * (a1 * (1 - a1)) * x[0,1]
w_n1_l1[2] = w_n1_l1[2] + alfa * (-2 * error * w_output[2]) * (a1 * (1 - a1)) * x[0,2]
w_n2_l1[0] = w_n2_l1[0] + alfa * (-2 * error * w_output[0]) * (a2 * (1 - a2)) * x[0,0]
w_n2_l1[1] = w_n2_l1[1] + alfa * (-2 * error * w_output[1]) * (a2 * (1 - a2)) * x[0,1]
w_n2_l1[2] = w_n2_l1[2] + alfa * (-2 * error * w_output[2]) * (a2 * (1 - a2)) * x[0,2]

print('Actualizacion del W en el hidden layer que da: ')
print(w_n1_l1)
print()
print(w_n2_l1)



Inicializacion en el leyer 1 de W en la neurona 1: 
[[ 0.96336888]
 [ 0.36735438]
 [-2.16350908]]

Z1 en el leyer 1 da: 
[[ 0.96336888]
 [ 0.        ]
 [-2.16350908]]

a1 en el leyer 1 da: 
0.23145027637760665

Inicializacion en el leyer 1 de W en la neurona 2: 
[[ 1.32129026]
 [-2.01031228]
 [ 1.80026371]]

Z2 en el leyer 1 da: 
[[ 1.32129026]
 [-0.        ]
 [ 1.80026371]]

a2 en el leyer 1 da: 
0.9577731210149977

y_hat en el output leyer da: 
[[-1.62289201]]

Actualizacion del W en el output layer que da: 
[[ 0.1459183 ]
 [-1.70988731]
 [ 0.11346046]]

Actualizacion del W en el hidden layer que da: 
[[ 0.9625264 ]
 [ 0.36735438]
 [-2.16416416]]

[[ 1.32109871]
 [-2.01031228]
 [ 1.80011476]]


In [50]:
def Stockastic_gradient_decent_net(x, y, lr=0.01, n_epochs=100):
    
    f = x.shape[0]
    c = x.shape[1]
    
    #w = np.random.randn(c).reshape(c,1)
    w_n1_l1 = np.random.normal(0,1,(c,1)) # dim = 3x1
    w_n2_l1 = np.random.normal(0,1,(c,1))
    w_output = np.random.normal(0,1,(c,1))

    for epoch in range(0,n_epochs):
        #idx = np.random.permutation(f)
        #x = x[idx]
        #y = y[idx]
        
        for n in range(0,f):
            # Hidden Layer - Neurona 1
            z1_l1 = x[n].T * w_n1_l1 # dim 3x1
            a1 = 1/ (1 + np.exp(-1* z1_l1.sum())) # dim 1x1

            # Hidden Layer - Neurona 2
            z2_l1 = x[n].T * w_n2_l1
            a2 = 1/ (1 + np.exp(-1* z2_l1.sum()))

            # Output Layer - Neurona salida
            y_hat = np.array([[a1,a2,1]]) @ w_output

            # Calculo del error 
            print('Epoch # {}, n = {}'.format(epoch, n))
            print(y_hat)
            print(y[n])
            error = y[n] - y_hat
            print(error)

            # Actualizacion de los parametros Output Layer

            w_output[0] = w_output[0] + lr * 2 * error * a1
            w_output[1] = w_output[1] + lr * 2 * error * a2
            w_output[0] = w_output[2] + lr * 2 * error 

            # Actualizacion de los parametros del Hidden Layer
            w_n1_l1[0] = w_n1_l1[0] + lr * (-2 * error * w_output[0]) * (a1 * (1 - a1)) * x[n,0]
            w_n1_l1[1] = w_n1_l1[1] + lr * (-2 * error * w_output[1]) * (a1 * (1 - a1)) * x[n,1]
            w_n1_l1[2] = w_n1_l1[2] + lr * (-2 * error * w_output[2]) * (a1 * (1 - a1)) * x[n,2]
            w_n2_l1[0] = w_n2_l1[0] + lr * (-2 * error * w_output[0]) * (a2 * (1 - a2)) * x[n,0]
            w_n2_l1[1] = w_n2_l1[1] + lr * (-2 * error * w_output[1]) * (a2 * (1 - a2)) * x[n,1]
            w_n2_l1[2] = w_n2_l1[2] + lr * (-2 * error * w_output[2]) * (a2 * (1 - a2)) * x[n,2]


    

In [51]:
Stockastic_gradient_decent_net(X, Y, lr=0.1 ,n_epochs=1000)

Se truncaron las últimas líneas 5000 del resultado de transmisión.
[[0.58106709]]
1
[[0.41893291]]
Epoch # 687, n = 3
[[0.63183305]]
0
[[-0.63183305]]
Epoch # 688, n = 0
[[0.43325928]]
0
[[-0.43325928]]
Epoch # 688, n = 1
[[0.37726773]]
1
[[0.62273227]]
Epoch # 688, n = 2
[[0.58074493]]
1
[[0.41925507]]
Epoch # 688, n = 3
[[0.63142716]]
0
[[-0.63142716]]
Epoch # 689, n = 0
[[0.43381318]]
0
[[-0.43381318]]
Epoch # 689, n = 1
[[0.37746712]]
1
[[0.62253288]]
Epoch # 689, n = 2
[[0.58042149]]
1
[[0.41957851]]
Epoch # 689, n = 3
[[0.63102247]]
0
[[-0.63102247]]
Epoch # 690, n = 0
[[0.4343669]]
0
[[-0.4343669]]
Epoch # 690, n = 1
[[0.37766685]]
1
[[0.62233315]]
Epoch # 690, n = 2
[[0.58009678]]
1
[[0.41990322]]
Epoch # 690, n = 3
[[0.63061908]]
0
[[-0.63061908]]
Epoch # 691, n = 0
[[0.43492038]]
0
[[-0.43492038]]
Epoch # 691, n = 1
[[0.3778669]]
1
[[0.6221331]]
Epoch # 691, n = 2
[[0.5797708]]
1
[[0.4202292]]
Epoch # 691, n = 3
[[0.63021705]]
0
[[-0.63021705]]
Epoch # 692, n = 0
[[0.43547356