In [1]:
import pandas as pd
import numpy as np

In [64]:
path = '/Users/francobenko/Documents/DataSets/TP6_INTRO/clase_6_dataset.txt'

In [65]:
class Data(object):

    def __init__(self, path):
        self.dataset = self._build_dataset(path)

    def split(self, percentage):
        train_data = np.random.permutation(self.dataset)[:int(self.dataset.shape[0]*percentage),:self.dataset.shape[1]]
        test_data = np.random.permutation(self.dataset[~(np.isin(self.dataset,train_data).sum(axis=1)==3),:])[:int(self.dataset.shape[0]*(1-percentage)),:self.dataset.shape[1]]
        return train_data, test_data


    def _build_dataset(self, path):
        data = np.genfromtxt(path, dtype=None, names=None, delimiter=',', encoding=None)
        return data.reshape(data.shape[0],1)

In [66]:
data = Data(path)

In [67]:
data.dataset[:5,:]

array([[(34.62365962, 78.02469282, 0)],
       [(30.28671077, 43.89499752, 0)],
       [(35.84740877, 72.90219803, 0)],
       [(60.18259939, 86.3085521 , 1)],
       [(79.03273605, 75.34437644, 1)]],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<i8')])

In [68]:
train_data, test_data = data.split(0.8)

In [113]:
def MBatch_gradient_decent(x_train, y_train, lr=0.01, n_epochs=100, b=10):
    
    f = x_train.shape[0]
    c = x_train.shape[1]
    
    w = np.random.randn(c).reshape(c,1)

    for epoch in range(0,n_epochs):
        idx = np.random.permutation(x_train.shape[0])
        x_train = x_train[idx]
        y_train = y_train[idx]
        
        batch_size = int(f/b)
        
        for n in range(0,f, batch_size):
            end = n + batch_size if n + batch_size <= f else f
            batch_x = x_train[n:end]
            batch_y = y_train[n:end]
            
            
            print (1/(1+(np.exp(-1*(np.sum(w.T * batch_x, axis=1))))))
            print('\n')
            print(1/(1+(np.exp(-1*(batch_x @ w)))))
            print ('\n')
            print (batch_y)
            
            grad = (batch_y - 1/(1+(np.exp(-1*(batch_x @ w)))))
            grad_sum = np.sum(grad * batch_x, axis = 0)
            grad_mul =  -2/f * grad_sum
            gradient = np.transpose(grad_mul).reshape(-1,1)
            w = w - (lr * gradient)

    return w

In [114]:
MBatch_gradient_decent(X,train_data['f2'])

[2.05600793e-32 2.75610162e-26 2.12233980e-26 8.50172986e-29
 9.45489310e-36 8.95669123e-29 2.52447230e-36 3.00282705e-23]


[[2.05600793e-32]
 [2.75610162e-26]
 [2.12233980e-26]
 [8.50172986e-29]
 [9.45489310e-36]
 [8.95669123e-29]
 [2.52447230e-36]
 [3.00282705e-23]]


[[1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]]
[1.91856119e-20 2.39863044e-29 2.08485810e-31 2.41236505e-19
 3.32630630e-24 1.71987410e-30 1.52601744e-18 3.14765440e-26]


[[1.91856119e-20]
 [2.39863044e-29]
 [2.08485810e-31]
 [2.41236505e-19]
 [3.32630630e-24]
 [1.71987410e-30]
 [1.52601744e-18]
 [3.14765440e-26]]


[[0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]]
[9.45220309e-20 1.60985072e-11 2.16895785e-16 1.53727450e-17
 1.85944325e-16 3.64562797e-15 1.88569508e-25 3.17588796e-20]


[[9.45220309e-20]
 [1.60985072e-11]
 [2.16895785e-16]
 [1.53727450e-17]
 [1.85944325e-16]
 [3.64562797e-15]
 [1.88569508e-25]
 [3.17588796e-20]]


[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]]
[3.02230910e-16 6.93746692e-22 7.04842712e-17 2.96941956e-18


 0.08923697 0.18498198]


[[0.16312359]
 [0.04682097]
 [0.12738298]
 [0.22994345]
 [0.17070388]
 [0.20028101]
 [0.08923697]
 [0.18498198]]


[[0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]]
[0.87853797 0.95493719 0.96366285 0.97658703 0.83676769 0.90598239
 0.92279169 0.94845703]


[[0.87853797]
 [0.95493719]
 [0.96366285]
 [0.97658703]
 [0.83676769]
 [0.90598239]
 [0.92279169]
 [0.94845703]]


[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]]
[0.15949228 0.21918514 0.12225059 0.15436819 0.10596664 0.30816455
 0.19456607 0.15065572]


[[0.15949228]
 [0.21918514]
 [0.12225059]
 [0.15436819]
 [0.10596664]
 [0.30816455]
 [0.19456607]
 [0.15065572]]


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
[0.999998   0.99999401 0.9999865  1.         0.99989773 0.99986769
 0.99999481 1.        ]


[[0.999998  ]
 [0.99999401]
 [0.9999865 ]
 [1.        ]
 [0.99989773]
 [0.99986769]
 [0.99999481]
 [1.        ]]


[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]]
[0.99446928 0.99945674 0.99925146 0.99905414 0.9996534  0.99953798
 0.9



[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]]
[0.00625401 0.01381771 0.0013726  0.00733174 0.00071725 0.00142082
 0.03377784 0.00720568]


[[0.00625401]
 [0.01381771]
 [0.0013726 ]
 [0.00733174]
 [0.00071725]
 [0.00142082]
 [0.03377784]
 [0.00720568]]


[[1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
[0.99888914 0.99854013 0.99909715 0.99839489 0.99955615 0.9906986
 0.9773     0.99987782]


[[0.99888914]
 [0.99854013]
 [0.99909715]
 [0.99839489]
 [0.99955615]
 [0.9906986 ]
 [0.9773    ]
 [0.99987782]]


[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]]
[0.99475    0.95792532 0.98407921 0.96447459 0.8517163  0.99597382
 0.99104079 0.9097496 ]


[[0.99475   ]
 [0.95792532]
 [0.98407921]
 [0.96447459]
 [0.8517163 ]
 [0.99597382]
 [0.99104079]
 [0.9097496 ]]


[[1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]]
[0.63105093 0.32414718 0.31740526 0.67701771 0.69475639 0.83094585
 0.40286195 0.15390407]


[[0.63105093]
 [0.32414718]
 [0.31740526]
 [0.67701771]
 [0.69475639]
 [0.83094585]
 [0.40286195]
 [0.15390407]]


[[0

 [0.00932052]]


[[1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]
[0.99780086 0.99785475 0.99993719 0.9977473  0.99922875 0.99784088
 0.99975442 0.99959558]


[[0.99780086]
 [0.99785475]
 [0.99993719]
 [0.9977473 ]
 [0.99922875]
 [0.99784088]
 [0.99975442]
 [0.99959558]]


[[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]]
[0.81433346 0.81827587 0.60116017 0.82645849 0.70603127 0.85673871
 0.64926367 0.75062229]


[[0.81433346]
 [0.81827587]
 [0.60116017]
 [0.82645849]
 [0.70603127]
 [0.85673871]
 [0.64926367]
 [0.75062229]]


[[0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]]
[0.37873893 0.22325189 0.11741843 0.2084051  0.4360572  0.27596767
 0.1880327  0.10034124]


[[0.37873893]
 [0.22325189]
 [0.11741843]
 [0.2084051 ]
 [0.4360572 ]
 [0.27596767]
 [0.1880327 ]
 [0.10034124]]


[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]
[0.91122865 0.91031753 0.68068504 0.96029798 0.91628851 0.89607606
 0.84709924 0.96179425]


[[0.91122865]
 [0.91031753]
 [0.68068504]
 [0.96029798]
 [0.91628851]
 [0.89607606]
 [0.84709924]
 [0.

[[0.74801472]
 [0.66112231]
 [0.61486691]
 [0.54033022]
 [0.43870624]
 [0.60113045]
 [0.52075131]
 [0.65559774]]


[[1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]]
[0.78705212 0.87164129 0.87649987 0.90365166 0.90071999 0.95002596
 0.96896941 0.93562297]


[[0.78705212]
 [0.87164129]
 [0.87649987]
 [0.90365166]
 [0.90071999]
 [0.95002596]
 [0.96896941]
 [0.93562297]]


[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]
[0.14512937 0.1176571  0.22744504 0.2784025  0.1636804  0.17938116
 0.1208453  0.15692927]


[[0.14512937]
 [0.1176571 ]
 [0.22744504]
 [0.2784025 ]
 [0.1636804 ]
 [0.17938116]
 [0.1208453 ]
 [0.15692927]]


[[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]
[0.99897034 0.99994528 0.99995665 0.999912   0.99998915 0.99877071
 0.99995851 0.99997169]


[[0.99897034]
 [0.99994528]
 [0.99995665]
 [0.999912  ]
 [0.99998915]
 [0.99877071]
 [0.99995851]
 [0.99997169]]


[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]]
[0.99863505 0.98839997 0.98622115 0.99859759 0.98279228 0.9991027
 0.98378679 0.99184556]


[[0.9


[[0.99974633]
 [0.99875697]
 [0.9980383 ]
 [0.9468646 ]
 [0.99292522]
 [0.99967221]
 [0.97777645]
 [0.94529389]]


[[1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]]
[0.72081617 0.18469007 0.73690825 0.85368698 0.41067959 0.58314285
 0.62765208 0.22156448]


[[0.72081617]
 [0.18469007]
 [0.73690825]
 [0.85368698]
 [0.41067959]
 [0.58314285]
 [0.62765208]
 [0.22156448]]


[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]
[0.12164365 0.26887194 0.92802306 0.75268958 0.26121856 0.70767396
 0.74820785 0.35524856]


[[0.12164365]
 [0.26887194]
 [0.92802306]
 [0.75268958]
 [0.26121856]
 [0.70767396]
 [0.74820785]
 [0.35524856]]


[[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]]
[0.98356361 0.91175034 0.90834898 0.89719554 0.92447616 0.97738834
 0.95127222 0.90620257]


[[0.98356361]
 [0.91175034]
 [0.90834898]
 [0.89719554]
 [0.92447616]
 [0.97738834]
 [0.95127222]
 [0.90620257]]


[[1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]]
[0.50211036 0.45545038 0.35550028 0.18341851 0.39738452 0.55257352
 0.12793354 0.17505919]


[[0



[[0.01657806]
 [0.05568512]
 [0.02168361]
 [0.0164989 ]
 [0.00740815]
 [0.02158077]
 [0.01498652]
 [0.01591258]]


[[1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]
[0.99994477 0.99997319 0.99992155 0.99999682 0.99998045 0.99999821
 0.99999798 0.99984719]


[[0.99994477]
 [0.99997319]
 [0.99992155]
 [0.99999682]
 [0.99998045]
 [0.99999821]
 [0.99999798]
 [0.99984719]]


[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]]
[0.99352971 0.99387878 0.99552031 0.99575726 0.98477131 0.98839143
 0.95567424 0.99410779]


[[0.99352971]
 [0.99387878]
 [0.99552031]
 [0.99575726]
 [0.98477131]
 [0.98839143]
 [0.95567424]
 [0.99410779]]


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]]
[0.8132482  0.83771751 0.94591745 0.96805154 0.94203966 0.97163627
 0.94869778 0.91939067]


[[0.8132482 ]
 [0.83771751]
 [0.94591745]
 [0.96805154]
 [0.94203966]
 [0.97163627]
 [0.94869778]
 [0.91939067]]


[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]]
[0.03746456 0.01257294 0.008951   0.00908824 0.02849057 0.03944505
 0.01565176 0.01928411]


[[

 0.97017284 0.99497547]


[[0.99700191]
 [0.98837434]
 [0.99245065]
 [0.97161873]
 [0.96180036]
 [0.96809886]
 [0.97017284]
 [0.99497547]]


[[1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]]
[0.00824534 0.00760603 0.00301642 0.0229671  0.01140408 0.08760286
 0.01746314 0.01632652]


[[0.00824534]
 [0.00760603]
 [0.00301642]
 [0.0229671 ]
 [0.01140408]
 [0.08760286]
 [0.01746314]
 [0.01632652]]


[[1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]]
[0.99783404 0.99914517 0.99692954 0.99518523 0.99960621 0.97417324
 0.99395361 0.99913836]


[[0.99783404]
 [0.99914517]
 [0.99692954]
 [0.99518523]
 [0.99960621]
 [0.97417324]
 [0.99395361]
 [0.99913836]]


[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]]
[0.20732848 0.44573174 0.41908234 0.43418946 0.4646371  0.46279418
 0.39871006 0.6736652 ]


[[0.20732848]
 [0.44573174]
 [0.41908234]
 [0.43418946]
 [0.4646371 ]
 [0.46279418]
 [0.39871006]
 [0.6736652 ]]


[[1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]]
[0.9970715  0.99438167 0.9930811  0.98109368 0.99826195 0.9761062
 0.99

 0.12807209 0.06006803]


[[0.01493354]
 [0.01617681]
 [0.03437764]
 [0.01720955]
 [0.06759704]
 [0.03190404]
 [0.12807209]
 [0.06006803]]


[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]
[0.99953949 0.98967277 0.99942046 0.99912641 0.9996658  0.99858197
 0.99898182 0.99900687]


[[0.99953949]
 [0.98967277]
 [0.99942046]
 [0.99912641]
 [0.9996658 ]
 [0.99858197]
 [0.99898182]
 [0.99900687]]


[[1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
[0.99147486 0.98786566 0.98353563 0.99600822 0.99226311 0.99308808
 0.99693278 0.99378977]


[[0.99147486]
 [0.98786566]
 [0.98353563]
 [0.99600822]
 [0.99226311]
 [0.99308808]
 [0.99693278]
 [0.99378977]]


[[1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]
[0.61460522 0.51476968 0.72721464 0.68255147 0.79505105 0.56931477
 0.77762015 0.63614965]


[[0.61460522]
 [0.51476968]
 [0.72721464]
 [0.68255147]
 [0.79505105]
 [0.56931477]
 [0.77762015]
 [0.63614965]]


[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]]
[0.71793597 0.73379191 0.82269146 0.8955492  0.78710074 0.76973177
 0.8

 [0.03420813]]


[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]]
[0.99999614 0.99999    0.99999874 0.999993   0.99991356 0.99996705
 0.99999262 0.99995782]


[[0.99999614]
 [0.99999   ]
 [0.99999874]
 [0.999993  ]
 [0.99991356]
 [0.99996705]
 [0.99999262]
 [0.99995782]]


[[1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]]
[0.9950228  0.98987509 0.99318523 0.99910913 0.99783329 0.99718293
 0.99837067 0.99882735]


[[0.9950228 ]
 [0.98987509]
 [0.99318523]
 [0.99910913]
 [0.99783329]
 [0.99718293]
 [0.99837067]
 [0.99882735]]


[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]
[0.74699685 0.47379441 0.70380496 0.49435176 0.78012753 0.80799167
 0.49829676 0.53266645]


[[0.74699685]
 [0.47379441]
 [0.70380496]
 [0.49435176]
 [0.78012753]
 [0.80799167]
 [0.49829676]
 [0.53266645]]


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
[0.94943275 0.98700773 0.88377959 0.98360355 0.95105853 0.96790403
 0.9854031  0.97376831]


[[0.94943275]
 [0.98700773]
 [0.88377959]
 [0.98360355]
 [0.95105853]
 [0.96790403]
 [0.9854031 ]
 [0.

 0.19051627 0.11492791]


[[0.17775414]
 [0.02368807]
 [0.02254604]
 [0.18703439]
 [0.28399061]
 [0.15451277]
 [0.19051627]
 [0.11492791]]


[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]]
[0.99787233 0.99977434 0.99759843 0.99316952 0.99282966 0.96787523
 0.99913693 0.98766282]


[[0.99787233]
 [0.99977434]
 [0.99759843]
 [0.99316952]
 [0.99282966]
 [0.96787523]
 [0.99913693]
 [0.98766282]]


[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]]
[0.20391485 0.24975685 0.16801056 0.79866967 0.3173029  0.32230897
 0.69007814 0.30219591]


[[0.20391485]
 [0.24975685]
 [0.16801056]
 [0.79866967]
 [0.3173029 ]
 [0.32230897]
 [0.69007814]
 [0.30219591]]


[[1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]]
[0.97461993 0.99676502 0.9957673  0.97599675 0.99556586 0.98633
 0.99716311 0.99686153]


[[0.97461993]
 [0.99676502]
 [0.9957673 ]
 [0.97599675]
 [0.99556586]
 [0.98633   ]
 [0.99716311]
 [0.99686153]]


[[0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]]
[0.48660396 0.33542022 0.57402319 0.38043063 0.42277079 0.4569819
 0.44963

array([[0.07359097],
       [0.01359341],
       [0.2271633 ]])

In [92]:
X = np.hstack((train_data['f0'],train_data['f1'],np.ones(train_data['f0'].shape)))

In [91]:
np.ones(len(train_data['f0'])).shape

(80,)

In [115]:
def mini_batch_logistic_regression(X_train, y_train, lr=0.01, amt_epochs=100):
    """
    shapes:
        X_t = nxm
        y_t = nx1
        W = mx1
    """
    b = 16
    m = X_train.shape[1]

    # initialize random weights
    W = np.random.randn(m).reshape(m, 1)

    for i in range(amt_epochs):
        idx = np.random.permutation(X_train.shape[0])
        X_train = X_train[idx]
        y_train = y_train[idx]

        batch_size = int(len(X_train) / b)
        for i in range(0, len(X_train), batch_size):
            end = i + batch_size if i + batch_size <= len(X_train) else len(X_train)
            batch_X = X_train[i: end]
            batch_y = y_train[i: end]

            exponent = np.sum(np.transpose(W) * batch_X, axis=1)
            prediction = 1/(1 + np.exp(-exponent))
            
            print(prediction)
            print(batch_y)

            error = prediction.reshape(-1, 1) - batch_y.reshape(-1, 1)

            grad_sum = np.sum(error * batch_X, axis=0)
            grad_mul = 1/b * grad_sum
            gradient = np.transpose(grad_mul).reshape(-1, 1)

            W = W - (lr * gradient)

    return W

In [116]:
mini_batch_logistic_regression(X,train_data['f2'])

[1.51378534e-01 1.00000000e+00 1.00000000e+00 1.00000000e+00
 8.51292750e-04]
[[1]
 [1]
 [0]
 [1]
 [1]]
[1.         0.99858668 1.         1.         1.        ]
[[0]
 [1]
 [1]
 [1]
 [1]]
[0.99999948 1.         1.         0.99999992 1.        ]
[[1]
 [1]
 [0]
 [0]
 [1]]
[1.         1.         0.9983161  1.         0.99998634]
[[0]
 [1]
 [0]
 [0]
 [1]]
[1.24846269e-19 7.62048409e-11 9.99999999e-01 1.00000000e+00
 9.99886502e-01]
[[0]
 [1]
 [0]
 [0]
 [1]]
[2.42884135e-03 1.01188943e-12 9.98661062e-01 4.19415508e-11
 1.00000000e+00]
[[1]
 [0]
 [0]
 [1]
 [1]]
[9.43584808e-01 1.68812484e-06 9.99999941e-01 9.99999995e-01
 3.51892377e-09]
[[1]
 [1]
 [1]
 [0]
 [1]]
[1.         1.         1.         0.99999972 1.        ]
[[1]
 [0]
 [1]
 [1]
 [1]]
[0.01658636 1.         1.         0.90646034 0.99999979]
[[0]
 [1]
 [1]
 [0]
 [0]]
[3.67089670e-08 1.39549676e-07 9.99925915e-01 9.99999182e-01
 1.00000000e+00]
[[1]
 [0]
 [0]
 [1]
 [1]]
[6.68971035e-13 1.66753841e-04 4.49996069e-12 1.00000000e+00
 2.4

 [1]]
[0.46657795 0.42276374 0.40130904 0.43796761 0.39134523]
[[0]
 [0]
 [1]
 [0]
 [1]]
[0.73147285 0.78337047 0.72728902 0.70528473 0.79502796]
[[1]
 [1]
 [1]
 [0]
 [1]]
[0.99295671 0.99174939 0.95300096 0.99532051 0.96751721]
[[1]
 [1]
 [0]
 [1]
 [0]]
[0.02867757 0.03487865 0.01042896 0.01150974 0.00848122]
[[1]
 [0]
 [0]
 [1]
 [1]]
[0.99999987 1.         0.99998358 0.99994509 0.99999126]
[[1]
 [1]
 [0]
 [0]
 [0]]
[0.61519965 0.96728176 0.84474914 0.95642321 0.66197819]
[[1]
 [1]
 [1]
 [1]
 [1]]
[0.97582096 0.99983397 0.98274736 0.99936427 0.99934165]
[[0]
 [1]
 [0]
 [1]
 [1]]
[0.30935536 0.77758681 0.35213379 0.9316324  0.90001487]
[[1]
 [1]
 [0]
 [0]
 [1]]
[0.46730205 0.29528918 0.54370845 0.34410789 0.29851543]
[[0]
 [0]
 [1]
 [1]
 [0]]
[0.98313108 0.95099437 0.87200565 0.82384845 0.85657129]
[[0]
 [1]
 [1]
 [1]
 [0]]
[0.02858762 0.06285565 0.05086512 0.0026808  0.00225695]
[[0]
 [0]
 [0]
 [1]
 [1]]
[0.9998086  0.99854796 0.99852812 0.99992414 0.99913523]
[[1]
 [0]
 [0]
 [1]
 [0]

[[0]
 [0]
 [0]
 [1]
 [1]]
[0.00076292 0.0126398  0.00058223 0.00363159 0.00028757]
[[1]
 [0]
 [1]
 [0]
 [1]]
[0.99999669 0.99982558 0.99977614 0.99999322 0.99999319]
[[1]
 [0]
 [0]
 [1]
 [1]]
[0.81920501 0.92455568 0.94334533 0.60118514 0.72481695]
[[0]
 [1]
 [1]
 [0]
 [1]]
[0.13281532 0.03833413 0.40230415 0.19299363 0.11314653]
[[0]
 [1]
 [1]
 [0]
 [1]]
[0.99961111 0.99997949 0.99999899 0.99994343 0.99999794]
[[0]
 [1]
 [1]
 [1]
 [1]]
[0.99602826 0.9904016  0.99495896 0.97925937 0.99995431]
[[0]
 [0]
 [0]
 [0]
 [0]]
[1.46159037e-10 7.87596858e-07 2.88653727e-07 8.25354668e-09
 1.50291056e-06]
[[1]
 [0]
 [0]
 [1]
 [0]]
[0.04081138 0.00646171 0.00821008 0.02020109 0.03939338]
[[1]
 [1]
 [0]
 [1]
 [1]]
[0.99999999 0.99999999 1.         1.         1.        ]
[[1]
 [1]
 [1]
 [1]
 [1]]
[0.99999997 1.         1.         1.         1.        ]
[[0]
 [1]
 [1]
 [1]
 [1]]
[0.99957421 0.99943115 0.99999915 0.99999172 1.        ]
[[0]
 [0]
 [1]
 [1]
 [1]]
[0.99925279 0.99996372 0.9996079  0.9999

 1.89993023e-04]
[[0]
 [1]
 [0]
 [1]
 [0]]
[0.75114472 0.43677541 0.90722241 0.84373514 0.1792066 ]
[[0]
 [1]
 [1]
 [1]
 [1]]
[0.99954574 0.99124224 0.99958533 0.99951811 0.99996073]
[[1]
 [0]
 [1]
 [1]
 [1]]
[0.97588346 0.96735707 0.9956899  0.93582662 0.90740179]
[[1]
 [1]
 [0]
 [1]
 [1]]
[0.16692147 0.49097584 0.13154881 0.34858566 0.28157398]
[[1]
 [0]
 [0]
 [1]
 [1]]
[0.99991619 0.99998647 0.99948858 0.99988828 0.99858702]
[[1]
 [1]
 [0]
 [1]
 [0]]
[0.32674388 0.67729135 0.15563529 0.83449345 0.41277378]
[[0]
 [0]
 [1]
 [1]
 [1]]
[0.99966813 0.99996047 0.99975888 0.9999452  0.99485408]
[[1]
 [1]
 [1]
 [1]
 [0]]
[0.90323251 0.96172287 0.82694027 0.85289113 0.58360575]
[[1]
 [1]
 [1]
 [0]
 [1]]
[0.96944199 0.9620634  0.86000217 0.97210803 0.98086213]
[[0]
 [0]
 [0]
 [1]
 [0]]
[2.08241230e-06 4.00107216e-06 2.26898294e-07 4.73301259e-07
 5.26693598e-05]
[[1]
 [0]
 [1]
 [1]
 [0]]
[0.99989661 0.95804163 0.94335392 0.95122029 0.99509706]
[[0]
 [0]
 [0]
 [0]
 [0]]
[7.47700575e-09 3.36681

[[1]
 [0]
 [0]
 [1]
 [1]]
[0.88928511 0.97611661 0.93091754 0.99509425 0.89700363]
[[0]
 [1]
 [0]
 [1]
 [0]]
[9.20608525e-05 1.93265076e-06 1.55790491e-03 1.31975280e-03
 1.44174144e-05]
[[0]
 [1]
 [0]
 [0]
 [1]]
[0.94399625 0.94112111 0.86503047 0.93828337 0.45917357]
[[1]
 [0]
 [0]
 [1]
 [1]]
[0.17905943 0.63798578 0.03411536 0.41005404 0.8675534 ]
[[0]
 [1]
 [1]
 [0]
 [0]]
[0.14751367 0.14241243 0.44364616 0.06436596 0.07053943]
[[1]
 [1]
 [1]
 [1]
 [1]]
[1.         1.         1.         1.         0.99999999]
[[1]
 [0]
 [1]
 [1]
 [0]]
[0.99999998 0.99999998 0.99999994 1.         0.99999964]
[[1]
 [1]
 [1]
 [1]
 [1]]
[0.99999219 0.99999966 0.99999974 0.99999999 0.99999999]
[[0]
 [1]
 [0]
 [1]
 [1]]
[0.99109551 0.9970501  0.95520525 0.99848828 0.99790826]
[[0]
 [1]
 [0]
 [1]
 [1]]
[0.06466451 0.13434193 0.08094568 0.23127071 0.35251018]
[[1]
 [0]
 [0]
 [0]
 [1]]
[0.99922071 0.99925358 0.9953247  0.98979921 0.99466295]
[[1]
 [1]
 [0]
 [0]
 [0]]
[0.00419025 0.00046747 0.00121265 0.0314

[[1]
 [1]
 [1]
 [1]
 [1]]
[0.99942254 0.99589496 0.99581773 0.99870002 0.99949378]
[[1]
 [1]
 [1]
 [1]
 [1]]
[0.99881359 0.9765106  0.98664086 0.99954336 0.99887968]
[[1]
 [0]
 [0]
 [1]
 [1]]
[0.08483253 0.05748523 0.18810702 0.07804167 0.05181636]
[[1]
 [1]
 [0]
 [1]
 [1]]
[1. 1. 1. 1. 1.]
[[1]
 [1]
 [1]
 [1]
 [1]]
[1.         1.         1.         0.99999999 1.        ]
[[1]
 [1]
 [1]
 [1]
 [1]]
[1.         1.         0.99999997 1.         0.99999998]
[[1]
 [0]
 [0]
 [1]
 [0]]
[0.97321727 0.98636673 0.98980938 0.99647938 0.99737385]
[[0]
 [0]
 [0]
 [1]
 [1]]
[0.00042053 0.02568786 0.0003732  0.00295449 0.00087302]
[[1]
 [0]
 [1]
 [0]
 [0]]
[0.99818372 0.98513232 0.99553771 0.99453066 0.99442977]
[[0]
 [0]
 [0]
 [0]
 [0]]
[2.20571265e-07 2.42656909e-05 2.03595878e-07 6.57221310e-06
 2.05817225e-07]
[[1]
 [0]
 [1]
 [0]
 [1]]
[0.94289261 0.98373122 0.95855225 0.96051611 0.93687517]
[[0]
 [1]
 [0]
 [0]
 [0]]
[1.26552931e-05 9.92390291e-06 1.87011080e-06 3.71960589e-06
 2.44516661e-05]
[[

[1.         1.         0.99999991 0.99999995 0.99999991]
[[0]
 [1]
 [0]
 [0]
 [0]]
[0.54184097 0.5777535  0.62154363 0.56280209 0.61434278]
[[1]
 [1]
 [1]
 [0]
 [0]]
[0.83186405 0.91235969 0.980318   0.90573077 0.98550841]
[[0]
 [0]
 [1]
 [0]
 [1]]
[0.00064255 0.00031771 0.00290545 0.00014516 0.00019938]
[[1]
 [0]
 [0]
 [1]
 [1]]
[0.9999296  0.9999884  0.99996975 0.99999979 0.99999993]
[[0]
 [0]
 [0]
 [1]
 [1]]
[0.24033645 0.40795656 0.31333189 0.33513637 0.35418313]
[[0]
 [0]
 [1]
 [0]
 [0]]
[0.0277664  0.02112191 0.04269587 0.10465247 0.02672587]
[[1]
 [1]
 [1]
 [0]
 [1]]
[1. 1. 1. 1. 1.]
[[1]
 [1]
 [1]
 [1]
 [1]]
[0.99999769 1.         1.         0.99999999 1.        ]
[[0]
 [1]
 [1]
 [0]
 [1]]
[0.99999787 0.99999695 0.99999983 0.99999831 0.99997388]
[[1]
 [1]
 [1]
 [1]
 [0]]
[0.99998362 0.99998486 0.99983369 0.99911375 0.99993216]
[[1]
 [1]
 [1]
 [0]
 [1]]
[0.9864824  0.96050068 0.98085974 0.99409741 0.98586783]
[[1]
 [0]
 [0]
 [0]
 [0]]
[4.09981482e-07 1.05431115e-07 3.40966748e-0

 [1]]
[0.96778313 0.98907154 0.97856525 0.99057303 0.99397472]
[[0]
 [1]
 [0]
 [0]
 [1]]
[5.01847814e-03 3.50803100e-05 7.27601047e-03 7.33921495e-05
 1.88434995e-05]
[[0]
 [1]
 [0]
 [1]
 [1]]
[0.99999323 0.99924361 0.99959253 0.99836785 0.99985825]
[[1]
 [0]
 [0]
 [0]
 [1]]
[0.03675984 0.0091223  0.02137107 0.00317818 0.00670886]
[[0]
 [1]
 [1]
 [1]
 [1]]
[0.99999998 0.9999997  0.99999997 1.         0.99999702]
[[0]
 [0]
 [1]
 [1]
 [0]]
[0.9851662  0.98144699 0.99251542 0.99366868 0.99170884]
[[1]
 [1]
 [1]
 [1]
 [0]]
[0.20712267 0.11183898 0.17183197 0.1217588  0.09820452]
[[0]
 [1]
 [1]
 [1]
 [1]]
[1.         1.         0.99998975 1.         0.99999929]
[[1]
 [1]
 [0]
 [1]
 [0]]
[0.99999389 0.99999828 0.99985597 0.9998865  0.99996097]
[[1]
 [1]
 [0]
 [0]
 [0]]
[0.12879622 0.16740951 0.27575468 0.17447022 0.18764611]
[[0]
 [1]
 [1]
 [1]
 [0]]
[0.999996   0.99956484 0.99954442 0.99999707 0.99958815]
[[1]
 [0]
 [0]
 [1]
 [0]]
[0.10846099 0.02021941 0.14583295 0.26202373 0.01395462]
[[0

array([[-0.00978534],
       [-0.06315094],
       [-0.06120323]])