In [1]:
import numpy as np 

# Ejercicio 1

In [2]:
mat_1 = np.array([[1,2,-3],[1,3,4],[5,2,0]], dtype=np.int64)

In [3]:
def l0 (mat):
    mask = mat != 0
    res = mask.sum()
    return res

In [4]:
mat_1_l0 = l0(mat_1)
mat_1_l0

8

In [5]:
def l1(mat):
    abs_values = np.absolute(mat)
    res = np.sum(abs_values,axis=1)
    return res

In [6]:
mat_1_l1 = l1(mat_1)
mat_1_l1

array([6, 8, 7])

In [7]:
def l2(mat):
    abs_values_powered = np.power(2,np.absolute(mat))
    squared_res = np.sqrt(np.sum(abs_values_powered, axis=1))
    return squared_res

In [8]:
mat_1_l2 = l2(mat_1)
mat_1_l2

array([3.74165739, 5.09901951, 6.08276253])

In [9]:
def linf (mat):
    abs_values = np.absolute(mat)
    res = abs_values.max()
    return res

In [10]:
mat_1_linf = linf(mat_1)
mat_1_linf

5

# Ejercicio 2

In [11]:
mat_2 = np.array([[3,8,-3],[1,3,4],[5,2,0]], dtype=np.int64)

In [12]:
mat_2_l2 = l2(mat_2)
mat_2_l2

array([16.4924225 ,  5.09901951,  6.08276253])

In [13]:
#arg_sort devuelve los indices de los valores ordenados de menor (posicion 0) a mayor (posicion n)
arg_sort_mat_2_l2 = np.argsort(mat_2_l2)
mat_2_l2[arg_sort_mat_2_l2]

array([ 5.09901951,  6.08276253, 16.4924225 ])

# Ejercicio 3

In [14]:
class List_Users(list):
     
    def get_id2idx(self):
        ind_num = list(range(0,np.max(self)+1))
        id2idx = [list(np.unique(self)).index(user) if ind_num[user] in self else -1 for user in ind_num]
        return id2idx
    
    def get_idx2id(self):
        return np.unique(self)
    
    def get_users_id (self):
        return self
    
    def get_users_idx(self):
        idx = np.array([list(np.unique(self)).index(user) for user in self])
        return idx    
    

In [15]:
list1_obj = List_Users(np.array([0,1,2,3,5,6,8,5,8,6,4], dtype=np.int64))

#list1_obj.get_id2idx()
#list1_obj.get_idx2id()
#list1_obj.get_users_id()
#list1_obj.get_users_idx()

In [16]:
class Indexer(object):
    def __init__(self, ids):
        unique_ids = np.unique(ids)
        id2idx = np.ones(unique_ids.max() + 1, dtype=np.int64) * -1
        id2idx[unique_ids] = np.arange(unique_ids.size)
        self.id2idx = id2idx
        self.idx2id = unique_ids
        
    def get_idxs(self, ids):
        ids = self.id2idx[ids]
        return ids, ids != -1
    
    def get_ids(self, idxs):
        return self.idx2id[idxs]

In [17]:
indexer_obj = Indexer(np.array([0,1,2,3,5,6,8,5,8,6,4], dtype=np.int64))

In [18]:
indexer_obj.get_ids(np.array([0,1,2,3,5,6,7,5,7,6,4], dtype=np.int64))

array([0, 1, 2, 3, 5, 6, 8, 5, 8, 6, 4])

# Ejercicio 4

In [19]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction =  np.array([1,1,1,1,0,0,1,1,0,0])

suma = truth+prediction
resta = truth-prediction
unos = np.ones(truth.size)

TP = np.sum(unos[suma == 2])
TN = np.sum(unos[suma == 0])
FP = np.sum(unos[resta == -1])
FN = np.sum(unos[suma == 1])


precision = TP/(TP+FP)
recall = TP/(TP+FN)
accuracy = (TP+TN)/(TP+FP+TN+FN)

print("La precision es: {}".format(precision))
print("La recall es {}".format(recall))
print("La accuracy es {}".format(accuracy))

La precision es: 0.5
La recall es 0.3333333333333333
La accuracy es 0.3076923076923077


In [20]:
class classification_metrics:
 
    def __init__(self, truth, prediction):
        self.suma = truth + prediction
        self.resta = truth - prediction
        self.TP = (suma == 2).sum()
        self.TN = (suma == 0).sum()
        self.FP = (resta == -1).sum()
        self.FN = (suma == 1).sum()
        
    
    def acc (self):
        accuracy = (self.TP+self.TN)/(self.TP+self.FP+self.TN+self.FN)
        return accuracy
    
    def precision (self):
        precision = self.TP/(self.TP+self.FP)
        return precision
    
    def recall (self):
        recall = self.TP/(self.TP+self.FN)
        return recall

In [21]:
classification_metrics(truth, prediction).recall()

0.3333333333333333

# Ejercicio 5

In [23]:
class avg_query_precision:
    
    def __call__(self, query_id, predicted_rank, truth_relevant):
        q_id_1_mask = (query_id ==1)
        prec_1 = truth_relevant[q_id_1_mask].sum()/truth_relevant[q_id_1_mask].size
        q_id_2_mask = (query_id ==2)
        prec_2 = truth_relevant[q_id_2_mask].sum()/truth_relevant[q_id_2_mask].size
        q_id_3_mask = (query_id ==3)
        prec_3 = truth_relevant[q_id_3_mask].sum()/truth_relevant[q_id_3_mask].size
        q_id_4_mask = (query_id ==4)
        prec_4 = truth_relevant[q_id_4_mask].sum()/truth_relevant[q_id_4_mask].size
        return prec_1+prec_2+prec_3+prec_4
        

In [24]:
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])
truth_relevance = np.array([True, False, True, False, True, True, True, False, False, False, False, False, True, False, False, True ])
k = 3

q_id_1_mask = (q_id ==1)
prec_1 = truth_relevance[q_id_1_mask].sum()/truth_relevance[q_id_1_mask].size
q_id_2_mask = (q_id ==2)
prec_2 = truth_relevance[q_id_2_mask].sum()/truth_relevance[q_id_2_mask].size
q_id_3_mask = (q_id ==3)
prec_3 = truth_relevance[q_id_3_mask].sum()/truth_relevance[q_id_3_mask].size
q_id_4_mask = (q_id ==4)
prec_4 = truth_relevance[q_id_4_mask].sum()/truth_relevance[q_id_4_mask].size


avg_q_prec = (prec_1+prec_2+prec_3+prec_4)/4
avg_q_prec

0.5

# Ejercicio 6

In [25]:
class avg_query_precision:
    
    def __call__(self, query_id, predicted_rank, truth_relevant, k):
        q_id_1_mask = (q_id ==1)
        prec_1 = truth_relevance[q_id_1_mask][0:k].sum()/truth_relevance[q_id_1_mask][0:k].size
        q_id_2_mask = (q_id ==2)
        prec_2 = truth_relevance[q_id_2_mask][0:k].sum()/truth_relevance[q_id_2_mask][0:k].size
        q_id_3_mask = (q_id ==3)
        prec_3 = truth_relevance[q_id_3_mask][0:k].sum()/truth_relevance[q_id_3_mask][0:k].size
        q_id_4_mask = (q_id ==4)
        prec_4 = truth_relevance[q_id_4_mask][0:k].sum()/truth_relevance[q_id_4_mask][0:k].size
        return (prec_1+prec_2+prec_3+prec_4)/4

In [26]:
avg = avg_query_precision()
avg(np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]), 
    np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]), 
    np.array([True, False, True, False, True, True, True, False, False, False, False, False, True, False, False, True ]),
   3)

0.49999999999999994

In [27]:
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])
truth_relevance = np.array([True, False, True, False, True, True, True, False, False, False, False, False, True, False, False, True ])
k = 3

q_id_1_mask = (q_id ==1)
prec_1 = truth_relevance[q_id_1_mask][0:k].sum()/truth_relevance[q_id_1_mask][0:k].size
q_id_2_mask = (q_id ==2)
prec_2 = truth_relevance[q_id_2_mask][0:k].sum()/truth_relevance[q_id_2_mask][0:k].size
q_id_3_mask = (q_id ==3)
prec_3 = truth_relevance[q_id_3_mask][0:k].sum()/truth_relevance[q_id_3_mask][0:k].size
q_id_4_mask = (q_id ==4)
prec_4 = truth_relevance[q_id_4_mask][0:k].sum()/truth_relevance[q_id_4_mask][0:k].size


avg_q_prec = (prec_1+prec_2+prec_3+prec_4)/4
avg_q_prec

0.49999999999999994

# Ejercicio 8

In [86]:
class structured_arrays:
    def __call__(self, path):
        data = np.genfromtxt(path, dtype='U60',delimiter=';')
        structure = [('header', np.dtype('U60')), 
            ('row', np.dtype('U60'), (data.shape[0]-1,))]
        structure = np.dtype(structure)
        st_arr = np.empty(data.shape[1], dtype=structure)
        st_arr['header'] = data[0,:]
        st_arr['row'] = data[1:,:].T
        return st_arr
        

In [89]:
path = '/Users/francobenko/Documents/DataSets/ejemplo.csv'

sta = structured_arrays()
st_array = sta(path)
st_array

array([('\ufeffcol_1', ['0.550149417', '0.350019969', '0.317120598', '0.865686808', '0.571398805', '0.194929997', '0.322266699', '0.703382034', '0.269670652', '0.536618609', '0.446635748', '0.05861478']),
       ('col_2', ['rojo', 'azul', 'verde', 'rojo', 'verde', 'violeta', 'rojo', 'verde', 'azul', 'violeta', 'rojo', 'rojo']),
       ('col_3', ['0.840236478', '0.813856354', '0.872336196', '0.414033291', '0.702426648', '0.58157983', '0.917508317', '0.010289638', '0.150438196', '0.019778364', '0.812730004', '0.53727344'])],
      dtype=[('header', '<U60'), ('row', '<U60', (12,))])

In [ ]:
#Create a .pkl of the object
import pickle

with open('dataset.pkl', 'wb') as file:
    pickle.dump(st_array,file,protocol=pickle.HIGHEST_PROTOCOL)