## Ejercicio 1

Calcular la distancia entre elemetos de X a cada elemento C

In [4]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

C = np.array([[1,0,0],[0,1,0]])

In [20]:
"""
Lo que hace esta linea de codigo es agrega una tercera dimension (como si fuera la profundidad) pasa de ser (2,3)
a ser (2,1,3)
"""
C_expandida = C[:,None]

In [12]:
dist = np.sqrt(np.sum((C_expandida-X)**2, axis=2))
dist

array([[ 3.60555128,  8.36660027, 13.45362405],
       [ 3.31662479,  8.24621125, 13.37908816]])

## Ejercicio 2

Devolver la posicion del centro mas cercano segun cada vector

In [16]:
min_dist = np.argmin(dist, axis=0)
min_dist

array([1, 1, 1])

## Ejercicio 3

Costo. Rehacer.

In [58]:
    
def k_mean(X, n, MAX_ITERATIONS):
    centroids = np.random.random_sample((n, X.shape[1]))+1
    for ite in range(MAX_ITERATIONS):
        print('Centroids:')
        print(centroids)
        print('Iteration # {}'.format(ite))
        centroids, min_dist = k_calculation(X, centroids)
    return centroids, min_dist

def k_calculation(X, centroids):
    centroids_expand = centroids[:,None]
    distance = np.sqrt(np.sum((centroids_expand-X)**2, axis=2))
    min_dist = np.argmin(distance, axis=0)
    centroids = k_min_centroid_search(min_dist, X)
    return centroids, min_dist

def k_min_centroid_search(min_dist, X):
    for i in range(centroids.shape[0]):
        centroids[i]= np.mean(X[min_dist==i,:], axis=0)
    return centroids

In [5]:
datos = np.random.normal(loc=0 , scale=1, size=(1000,2))

array([[-0.20075948, -0.44729614],
       [ 0.71886331, -1.43164618],
       [ 0.34697399, -0.62849253],
       ...,
       [-1.42811894,  1.30021256],
       [ 1.75334739,  1.10424298],
       [-0.58463059,  1.10164609]])

In [59]:
Centroids, labels = k_mean(datos,3,10)

Centroids:
[[1.06031202 1.98633877]
 [1.90693949 1.82701592]
 [1.29469431 1.83095678]]
Iteration # 0
Centroids:
[[-0.68058467  0.45915399]
 [ 2.11329831  0.05864584]
 [ 0.47920282 -0.40566982]]
Iteration # 1
Centroids:
[[-0.68043708  0.51253557]
 [ 1.73123147  0.41395178]
 [ 0.31772894 -0.56784221]]
Iteration # 2
Centroids:
[[-0.68158591  0.59505125]
 [ 1.40338865  0.51437552]
 [ 0.13665901 -0.75406297]]
Iteration # 3
Centroids:
[[-0.6912611   0.62288826]
 [ 1.21606694  0.51598096]
 [ 0.02088535 -0.86813598]]
Iteration # 4
Centroids:
[[-0.68715984  0.66055526]
 [ 1.11438087  0.46395133]
 [-0.09167731 -0.93376057]]
Iteration # 5
Centroids:
[[-0.67021537  0.67841893]
 [ 1.06925102  0.40486632]
 [-0.17151342 -0.98488453]]
Iteration # 6
Centroids:
[[-0.65732098  0.69911451]
 [ 1.05058374  0.34885833]
 [-0.22277706 -1.00917574]]
Iteration # 7
Centroids:
[[-0.64643861  0.72273582]
 [ 1.03562426  0.28854668]
 [-0.28455442 -1.02234407]]
Iteration # 8
Centroids:
[[-0.63239157  0.73966773]
 [ 1.

## Ejercicio 4

Cuando decimos alejar, no es sinonimo de desplazar, por ejemplo si le sumamos algo estariamos cambiando el centroide no alejandolos. Puede ser?

In [78]:
def syntetic_data(number_samples, far):
    centroids = np.array([[1,0,0,0],[0,1,0,0]])
    centroids_far = centroids*far
    data = np.repeat(centroids_far, number_samples/2, axis=0)
    normal_noise = np.random.normal(loc=0, scale=1, size=(number_samples,4))
    data = data + normal_noise
    cluster_ids = np.array([[0],[1],])
    cluster_ids = np.repeat(cluster_ids, number_samples/2, axis=0)
    
    return data, cluster_ids
    
    
    
    


In [89]:
data, cluster_ids = syntetic_data(1000,5)

In [90]:
import seaborn as sns

sns.scatterplot(x=data[:,0], y=data[:,1], hue=cluster_ids[:,0])

# Simulacion de variables aleatoreas

## Ejercicio 5

In [101]:


def random_exp_samples (number_samples):
    va_unif = np.random.uniform(low=0., high=1., size=number_samples)
    va_exp = -(np.log(1-va_unif))/2
    fig = plt.figure(figsize=(12,6)) 
    ax0 = fig.add_subplot(1,2,1)
    ax1 = fig.add_subplot(1,2,2)
    
    ax0 = sns.distplot(va_unif[:,0], ax=ax0)
    ax0.set_title('Displot VA Generadora')
    
    ax1 = sns.distplot(va_exp[:,0], ax=ax1)
    ax1.set_title('Displot VA Salida')
    return va_exp

# pasar a funcion

In [102]:
data = random_exp_samples((1000,1))

## Ejercicio 6

si FX(x) = x^3 La inversa generalizada seria x^1/3

In [20]:
def simul_x3(samples):
    va_unif = np.random.uniform(low=0., high=1., size=samples)
    data_simul_unif = np.cbrt(va_unif)
    
   
    fig, ((ax2, ax3)) = plt.subplots(1, 2, figsize=(12, 5))
    
    ax2 = sns.distplot(va_unif[:,0], ax=ax2)
    ax2.set_title('Displot VA Generadora uniforme')
    
    ax3 = sns.distplot(data_simul_unif[:,0], ax=ax3)
    ax3.set_title('Displot VA Salida')
    
    return data_simul_unif

In [21]:
n_samples = (5000,1)

data_simul_unif = simul_x3(n_samples)

## Ejercicio 7

In [56]:
def z_score(datos):
    std = np.std(datos, axis=0)
    mean = np.mean(datos, axis=0)
    data_norm = (datos - mean)/std
    return data_norm

In [57]:
a = np.array([[1,4,1],[1,1,1],[6,3,4],[1,1,7],[1,2,1]])

In [58]:
z_score(a)

array([[-0.5       ,  1.54348727, -0.75      ],
       [-0.5       , -1.02899151, -0.75      ],
       [ 2.        ,  0.68599434,  0.5       ],
       [-0.5       , -1.02899151,  1.75      ],
       [-0.5       , -0.17149859, -0.75      ]])

# Ejercicio 8

Crear un pca casero.

In [23]:
x = np.array([[0.4, 4800, 5.5], [0.7, 12104, 5.2], [1, 12500, 5.5], [1.5, 7002, 4.0]])

In [50]:
def pca_casero(datos):
    mean = np.mean(datos, axis=0)
    x_sinmedia = datos - mean
    x_sin_transp = np.transpose(x_sinmedia)
    x_cov = np.cov(x_sin_transp)
    autoval, autovec = np.linalg.eig(x_cov)
    agsort_masc_autovec = np.argsort(autoval)[::-1]
    sort_autoval = autoval[agsort_masc_autovec]
    sort_autovec = autovec[:,agsort_masc_autovec]
    datos_comp = np.matmul(x_sinmedia,sort_autovec)
    return datos_comp

In [51]:
pca_casero(x)

array([[-4.30149998e+03, -8.02326173e-01, -1.95208313e-03],
       [ 3.00250000e+03, -1.28909759e-01,  2.06688738e-01],
       [ 3.39850002e+03, -2.01714182e-01, -1.92583562e-01],
       [-2.09950004e+03,  1.13295011e+00, -1.21530926e-02]])

Probar si da lo mismo que la funcion de scikit learn.

In [22]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
x = np.array([ [0.4, 4800, 5.5], [0.7, 12104, 5.2], [1, 12500, 5.5], [1.5, 7002, 4.0] ])
pca = PCA(n_components=3)
x_std = StandardScaler(with_std=False).fit_transform(x)
pca.fit_transform(x_std)

array([[ 4.30149998e+03, -8.02326173e-01, -1.95208313e-03],
       [-3.00250000e+03, -1.28909759e-01,  2.06688738e-01],
       [-3.39850002e+03, -2.01714182e-01, -1.92583562e-01],
       [ 2.09950004e+03,  1.13295011e+00, -1.21530926e-02]])

## Ejercicio 9

In [149]:
def col_isna_delete (y):
    na_rows_mask = (np.isnan(y).sum(axis=0) >= y.shape[0]*0.5)
    data_wh_na = y[:,~(na_rows_mask)]
    return data_wh_na

In [145]:
y2 = np.array([ [0.5, np.nan, 5.9],[0.4, np.nan , 5.5], [0.8, np.nan, 4.5],[np.nan, 12104, 5.2], [1, np.nan, 5.5], [1.5, 7002, np.nan] ])
y2

array([[5.0000e-01,        nan, 5.9000e+00],
       [4.0000e-01,        nan, 5.5000e+00],
       [8.0000e-01,        nan, 4.5000e+00],
       [       nan, 1.2104e+04, 5.2000e+00],
       [1.0000e+00,        nan, 5.5000e+00],
       [1.5000e+00, 7.0020e+03,        nan]])

In [150]:
col_isna_delete(y2)

array([[0.5, 5.9],
       [0.4, 5.5],
       [0.8, 4.5],
       [nan, 5.2],
       [1. , 5.5],
       [1.5, nan]])

## Ejercicio 10

Mean imputer

In [133]:
def col_isna_avg_imp (y):
    na_rows_mask = (np.isnan(y).sum(axis=1) >= 1)
    na_mean_imput = np.where(~(np.isnan(y)), y, y[~(na_rows_mask)].mean(axis=0))
    return na_mean_imput
    

In [109]:
y = np.array([ [0.5, 9000, 5.9],[0.4, np.nan , 5.5], [0.8, 1500, 4.5],[np.nan, 12104, 5.2], [1, 12500, 5.5], [1.5, 7002, np.nan] ])
y

array([[5.0000e-01, 9.0000e+03, 5.9000e+00],
       [4.0000e-01,        nan, 5.5000e+00],
       [8.0000e-01, 1.5000e+03, 4.5000e+00],
       [       nan, 1.2104e+04, 5.2000e+00],
       [1.0000e+00, 1.2500e+04, 5.5000e+00],
       [1.5000e+00, 7.0020e+03,        nan]])

In [134]:
col_isna_avg_imp(y)

array([[5.00000000e-01, 9.00000000e+03, 5.90000000e+00],
       [4.00000000e-01, 7.66666667e+03, 5.50000000e+00],
       [8.00000000e-01, 1.50000000e+03, 4.50000000e+00],
       [7.66666667e-01, 1.21040000e+04, 5.20000000e+00],
       [1.00000000e+00, 1.25000000e+04, 5.50000000e+00],
       [1.50000000e+00, 7.00200000e+03, 5.30000000e+00]])

## Ejercicio 11

In [209]:
#Posibles repeticiones
def splitter_dataset_702010r(dataset):
    train_data = np.random.permutation(dataset)[:int(dataset.shape[0]*0.7),:dataset.shape[1]]
    valid_data = np.random.permutation(dataset)[:int(dataset.shape[0]*0.2),:dataset.shape[1]]
    test_data = np.random.permutation(dataset)[:int(dataset.shape[0]*0.1),:dataset.shape[1]]
    return train_data, valid_data, test_data

In [236]:
#Sin repeticiones
def splitter_dataset_702010(dataset):
    train_data = np.random.permutation(dataset)[:int(dataset.shape[0]*0.7),:dataset.shape[1]]
    valid_data = np.random.permutation(dataset[~(np.isin(dataset,train_data).sum(axis=1)==3),:])[:int(dataset.shape[0]*0.2),:dataset.shape[1]]
    valid_dataset = dataset[~(np.isin(dataset,train_data).sum(axis=1)==3),:]
    test_data = np.random.permutation(valid_dataset[~(np.isin(valid_dataset,valid_data).sum(axis=1)==3),:])[:(dataset.shape[0]-train_data.shape[0]-valid_data.shape[0]),:dataset.shape[1]]
    return train_data, valid_data, test_data


In [151]:
y3 = np.array([ [0.5, 9000, 5.9],[0.4, 5822 , 5.5], [0.8, 1500, 4.5],[1.9, 12104, 5.2], [1, 12500, 5.5], [1.5, 7002, 6.0] ])
y3

array([[5.0000e-01, 9.0000e+03, 5.9000e+00],
       [4.0000e-01, 5.8220e+03, 5.5000e+00],
       [8.0000e-01, 1.5000e+03, 4.5000e+00],
       [1.9000e+00, 1.2104e+04, 5.2000e+00],
       [1.0000e+00, 1.2500e+04, 5.5000e+00],
       [1.5000e+00, 7.0020e+03, 6.0000e+00]])

In [237]:
splitter_dataset_702010(y3)

(array([[5.000e-01, 9.000e+03, 5.900e+00],
        [1.000e+00, 1.250e+04, 5.500e+00],
        [8.000e-01, 1.500e+03, 4.500e+00],
        [1.500e+00, 7.002e+03, 6.000e+00]]),
 array([[4.000e-01, 5.822e+03, 5.500e+00]]),
 array([[1.9000e+00, 1.2104e+04, 5.2000e+00]]))

## Ejercicio 12